# Site settings
title: taue	
email:
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://syon.github.io"
twitter_username:
github_username:  syon

# Build settings
markdown: kramdown
permalink: pretty

# Google Analytics
google_analytics: UA-37634759-2
